# Cloudflare Wrangler Configuration File for ENDD Alliance Pages Project

name = "endd-alliance"
pages_build_output_dir = "_site"

[[d1_databases]]
binding = "DB"
database_name = "endd-alliance-db-stage"
database_id = "dd0ce1a7-90f5-4032-8058-d049ac850b19"

[ai]
binding = "AI"
